name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[accel]
        pip install pytest pytest-cov ruff mypy
    
    - name: Lint with ruff
      run: |
        ruff check bhut/ --ignore=E501,F401,F841,B007
    
    - name: Type check with mypy (non-strict)
      run: |
        mypy bhut/ --ignore-missing-imports --follow-imports=silent --no-strict-optional --allow-untyped-defs --allow-incomplete-defs --allow-untyped-calls || echo "Type checking completed with warnings"
    
    - name: Test with pytest
      run: |
        pytest -q --maxfail=1 --disable-warnings --cov=bhut

  test-optional-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        optional-deps: ["dask"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[accel]
        pip install pytest pytest-cov
    
    - name: Install optional dependency - ${{ matrix.optional-deps }}
      run: |
        if [ "${{ matrix.optional-deps }}" = "dask" ]; then
          pip install 'dask[array]>=2024.1.0'
        fi
    
    - name: Test with optional dependencies
      run: |
        pytest tests/test_dask.py -q --maxfail=1 --disable-warnings --cov=bhut
